// <auto-generated />
namespace Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class index_on_usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(index_on_usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "201906291328116_index_on_usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
