// <auto-generated />
namespace Dominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fk_barrio_en_vivienda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_barrio_en_vivienda));
        
        string IMigrationMetadata.Id
        {
            get { return "201906191235308_fk_barrio_en_vivienda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
